title: Shixuan Gu
url: "https://shixuangu.github.io."
baseurl: "/ShixuanGu.github.io"

markdown: kramdown
# ins_logo: "./goose.jpg"

tracking_id: #

footer: yes
jekyll_url: "https://jekyllrb.com/"
theme_url: "https://github.com/ankitsultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/ShixuanGu.github.io"
 - name: "Contact"
   link: "contact"
 - name: "CV"
   link: "CV_Shixuan_Gu.pdf"

